name = "salesledger"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "salesledger-db"
database_id = "1a88bdc1-98a3-462f-8f48-8dad0730f6ad"

[vars]
ENV = "development"
# 生产密码通过 Cloudflare Secret 配置
# 本地开发时可以临时添加: ACCESS_KEY = "1234"
